--Create Database
CREATE DATABASE TicketSelling;

--Using Database
USE TicketSelling

--Create table User
CREATE TABLE USERS 
(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_User AS 'UID' + RIGHT('00000000' + CAST(ID AS VARCHAR(8)),8) PERSISTED PRIMARY KEY,
	First_Name VARCHAR(50) NOT NULL,
	Last_Name VARCHAR(50) NOT NULL,
	Phone CHAR(20) NOT NULL,
	Address_User NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	Gender_User CHAR(10) NOT NULL,
	Date_Of_Birth DATE  NOT NULL,
	Role_User VARCHAR(15)
);


--Create table Account
CREATE TABLE ACCOUNT
(
	Username NVARCHAR(50) PRIMARY KEY,
	Pass_Account NVARCHAR(50) NOT NULL,
	ID_User VARCHAR(11) FOREIGN KEY REFERENCES USERS (ID_User)
	
);

--Create table Trip
CREATE TABLE TRIP
(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_Trip AS 'TID' + RIGHT('00000000' + CAST(ID AS VARCHAR(8)),8) PERSISTED PRIMARY KEY,
	Source VARCHAR(50) NOT NULL,
	Destination VARCHAR(50) NOT NULL,
	Date_Trip DATE NOT NULL,
	Start_Time TIME NOT NULL,
	Arrival_Time TIME NOT NULL,
	Duration TIME NOT NULL,
	Total_Seat INT NOT NULL,
	Available_Seat INT NOT NULL,
	Price INT NOT NULL,
	Discount FLOAT NOT NULL,
	ID_Driver VARCHAR(11) FOREIGN KEY REFERENCES USERS(ID_User),
	ID_Manager VARCHAR(11) FOREIGN KEY REFERENCES USERS(ID_User)
);

--Create table Ticket
CREATE TABLE TICKET 
(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_Ticket AS 'TKID' + RIGHT('00000000' + CAST(ID AS VARCHAR(8)),8) PERSISTED PRIMARY KEY,
	Seat_Number INT NOT NULL,
	Total_Price BIGINT,
	ID_User VARCHAR(11) FOREIGN KEY REFERENCES USERS (ID_User),
	ID_Trip VARCHAR(11) FOREIGN KEY REFERENCES TRIP (ID_Trip)
);

--Create table Payment
CREATE TABLE PAYMENT
(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_Bill AS 'PID' + RIGHT('00000000' + CAST(ID AS VARCHAR(8)),8) PERSISTED PRIMARY KEY,
	Name VARCHAR(50),
	Bank VARCHAR(50),
	Card_Number INT,
	Card_Type VARCHAR(50),
	ID_Ticket VARCHAR(12) FOREIGN KEY REFERENCES dbo.TICKET (ID_Ticket)

);
