--Create Database
CREATE DATABASE TicketSelling;

--Using Database
USE TicketSelling

--Create table Guest
CREATE TABLE DRIVER
(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_Driver AS 'DID' + RIGHT('00000000' + CAST(ID AS VARCHAR(8)),8) PERSISTED PRIMARY KEY,
	Name_Driver VARCHAR(50) NOT NULL,
	Phone_Driver CHAR(20) NOT NULL,
	Address_Driver NVARCHAR(50) NOT NULL,
	Gender_Driver CHAR(10) NOT NULL,
	Date_Of_Birth_Driver DATE NOT NULL
);

--Create table User
CREATE TABLE USERS 
(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_User AS 'UID' + RIGHT('00000000' + CAST(ID AS VARCHAR(8)),8) PERSISTED PRIMARY KEY,
	Name_User VARCHAR(50) NOT NULL,
	Phone_User CHAR(20) NOT NULL,
	Address_User NVARCHAR(50) NOT NULL,
	Email_User NVARCHAR(50) NOT NULL,
	Gender_User CHAR(10) NOT NULL,
	Date_Of_Birth DATE  NOT NULL
);

--Create table Manager
CREATE TABLE MANAGER
(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_Manager AS 'MID' + RIGHT('00000000' + CAST(ID AS VARCHAR(8)),8) PERSISTED PRIMARY KEY,
	Name_Manager VARCHAR(50) NOT NULL,
	Phone_Manager CHAR(20) NOT NULL,
	Address_Manager NVARCHAR(50) NOT NULL,
	Email_Manager NVARCHAR(50) NOT NULL,
	Gender_Manager CHAR(10) NOT NULL,
	Date_Of_Birth_Manager DATE  NOT NULL
);
CREATE TABLE GUESTS
(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_Guest AS 'GID' + RIGHT('00000000' + CAST(ID AS VARCHAR(8)),8) PERSISTED PRIMARY KEY,
	Name_Guest VARCHAR(50) NOT NULL,
	Phone_Guest CHAR(20) NOT NULL,
	Address_Guest NVARCHAR(50) NOT NULL,
	Email_Guest NVARCHAR(50) NOT NULL,
	Gender_Guest CHAR(10) NOT NULL,
	Date_Of_Birth_Guest DATE NOT NULL,
	ID_User VARCHAR(11) FOREIGN KEY REFERENCES USERS (ID_User)
);

--Create table Account
CREATE TABLE ACCOUNT
(
	Username NVARCHAR(50) NOT NULL,
	Pass_Account NVARCHAR(50) NOT NULL,
	ID_User VARCHAR(11) FOREIGN KEY REFERENCES USERS(ID_User),
	ID_Manager VARCHAR(11) FOREIGN KEY REFERENCES MANAGER(ID_Manager)
);

--Create table Trip
CREATE TABLE TRIP
(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_Trip AS 'TID' + RIGHT('00000000' + CAST(ID AS VARCHAR(8)),8) PERSISTED PRIMARY KEY,
	Source VARCHAR(50) NOT NULL,
	Destination VARBINARY(50) NOT NULL,
	Date_Trip DATE NOT NULL,
	Start_Time TIME NOT NULL,
	Arrival_Time TIME NOT NULL,
	Duration TIME NOT NULL,
	Total_Seat INT NOT NULL,
	Available_Seat INT NOT NULL,
	Price INT NOT NULL,
	Discount FLOAT NOT NULL,
	ID_Driver VARCHAR(11) FOREIGN KEY REFERENCES DRIVER(ID_Driver)
);

--Create table Ticket
CREATE TABLE TICKET 
(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_Ticket AS 'TKID' + RIGHT('00000000' + CAST(ID AS VARCHAR(8)),8) PERSISTED PRIMARY KEY,
	ID_User VARCHAR(11) FOREIGN KEY REFERENCES USERS(ID_User),
	ID_Trip VARCHAR(11) FOREIGN KEY REFERENCES TRIP(ID_Trip),
	Seat_Number INT NOT NULL
);

--Create table Bill
CREATE TABLE BILL
(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_Bill AS 'BID' + RIGHT('00000000' + CAST(ID AS VARCHAR(8)),8) PERSISTED PRIMARY KEY,
	ID_Ticket VARCHAR(12) FOREIGN KEY REFERENCES TICKET(ID_Ticket),
	ID_User VARCHAR(11) FOREIGN KEY REFERENCES USERS(ID_User),
	ID_Trip VARCHAR(11) FOREIGN KEY REFERENCES TRIP(ID_Trip)
);
